language: php

php:
  - 5.3
  - 5.4

#env:
#  - SYMFONY_VERSION=v2.0.15
#  - SYMFONY_VERSION=origin/2.0
#  - SYMFONY_VERSION=origin/master

before_script:
  - mysql -e 'create database alphalemon_test;'
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - php app/console alphalemon:install-cms --company=Acme --bundle=WebSiteBundle --dsn="mysql:host=localhost;port=3306;dbname=alphalemon_test" --user=root --password= --no-interaction

script: phpunit -c app

notifications:
  email:
    - info@alphalemon.com
